apiVersion: v1
kind: Pod
metadata:
  name: pod-declarativo
  labels:
    app: label-pod-declarativo
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
