apiVersion: v1
kind: Pod
metadata:
  name: pod-declarativo1
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: nginx-container1
      image: nginx:latest
      ports:
        - containerPort: 80
