#versão da API do script
apiVersion: v1
#tipo da criação, neste caso um serviço
kind: Service
#informações referentes ao serviço
metadata:
#nome do serviço
  name: svc-pod-1
#especificações do serviço
spec:
  type: NodePort
  selector:
    app: primeiro-pod
  ports:
    - port: 8008
      targetPort: 80
      nodePort: 30000
