version: '3'
services:
  proxy:
    image: helloworldimg
    container_name: helloworld
    build:
      context: .
    #volumes: 
    #  - .\site:/usr/share/nginx/htm
    #volumes: 
    #  - site:/usr/share/nginx/htm
    ports:
      - "8000:80"
    networks:
      - webservereth

networks: 
  webservereth:
    driver: bridge

#volumes:
#  site:

    # docker-compose up -d