apiVersion: v1
kind: Pod
metadata:
  name: pod-declarativo2
  labels:
    app: segundo-pod
spec:
  containers:
    - name: nginx-container2
      image: nginx:latest
      ports:
        - containerPort: 80
