#versão da API do script
apiVersion: v1
#tipo da criação, neste caso um serviço
kind: service
#informações referentes ao serviço
metadata:
#nome do serviço
  name: svc-pod-2
#especificações do serviço
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
    - port: 8087
      targetPort: 80
